# @package _global_

model_name: deepconn

data:
  review_length: 40
  review_count: 10
  lowest_r_count: 1
  retain_rui: false
  pad_id: 0
  unk_id: 1
  load_review_text: true

w2v:
  embedding_dim: 64
  window: 1
  min_count: 1
  workers: 4
  sg: 1
  negative: 64
  max_vocab: 50000
  epochs: 20

model:
  freeze_word_embedding: false
  hidden_dim: 64
  num_filters: 100
  kernel_size: 3
  dropout: 0.1
  fm_k: 10

training:
  batch: 256
  eval_batch: 512
  epoch: 600
  lr: 0.001
  weight_decay: 0.0
  lr_decay: 0
  optimizer: Adam