# @package _global_
model_name: letter

model:
  hidden: 128
  pivot: 3
  edge_ratio: 50
  CL: 0
  aa: 0
  reg_lr: 1.0
  cl_lr: 1.0
  aa_lr: 1.0

training:
  batch: 128
  eval_batch: 128
  epoch: 1000
  lr: 0.0005
  weight_decay: 1e-4
  lr_decay: 0.99
  optimizer: Adam

evaluation:
  eval_step: 1
  early_stop_patience: 15

data:
  root: /home/infolab/mnt/mingyu/review_rec/dataset
  cache_dir: /home/infolab/mnt/mingyu/review_rec/review4rec/cached
  dataset: Amazon_All_Beauty_18
  language_model: "bert_whitening"
  plm_embedding: false
  embedding_batch_size: 32
  bert_whitening_dim: 64
  load_review_text: false
  separator: "\t"
  columns:
    user_id: user_id
    item_id: item_id
    timestamp: timestamp
    rating: rating
    review_text: reviewText
    review_embedding: review_embedding
  split:
    train_ratio: 0.8
    valid_ratio: 0.1

experiment:
  seed: 42
  device: 0
  save_dir: ./outputs
  log_step: 10

stats:
  num_users: 0
  num_items: 0
