# @package _global_
model_name: letter

model:
  embedding_dim: 128
  hidden_dim: 64
  dropout: 0.3
  edge_ratio: 50

data:
  type: bert

training:
  lr: 0.0005
  batch: 64
  eval_batch: 512
  epoch: 1000
  weight_decay: 1e-3
  lr_decay: 0.99
  optimizer: Adam
  grad_clip: 1.0

evaluation:
  eval_step: 1
  early_stop_patience: 15
