# @package _global_
model_name: mymodel

model:
  d_id: 64 #cf embedding dimension
  d_model: 32 # hidden dimension
  d_text : 256 # review projection dimension
  dropout: 0.2
  num_layers: 3

training:
  batch: 128
  eval_batch: 256
  epoch: 100
  lr: 0.001
  weight_decay: 2e-5
  lr_decay: 0.99
  optimizer: Adam

evaluation:
  eval_step: 1
  early_stop_patience: 20

data:
  root: /home/infolab/mnt/mingyu/review_rec/dataset
  cache_dir: /home/infolab/mnt/mingyu/review_rec/review4rec/cached
  dataset: Amazon_All_Beauty_18
  language_model: "sentence-transformers/all-MiniLM-L6-v2"
  plm_embedding : true
  embedding_batch_size: 16
  plm_embedding_size: 384
  load_review_text: true
  stopword_file: /home/infolab/mnt/mingyu/review_rec/review4rec/cached/word2vec/stopwords.txt
  punctuation_file: /home/infolab/mnt/mingyu/review_rec/review4rec/cached/word2vec/punctuations.txt
  separator: "\t"
  retain_rui : true
  columns:
    user_id: user_id
    item_id: item_id
    timestamp: timestamp
    rating: rating
    review_text: reviewText
    review_embedding: review_embedding
  split:
    train_ratio: 0.8
    valid_ratio: 0.1

experiment:
  seed: 42
  device: 0
  save_dir: ./outputs
  log_step: 10

stats:
  num_users: 0
  num_items: 0
