# @package _global_
model_name: mymodel_v2


model:
  hidden_dim: 64
  num_filters: 100
  kernel_size: 3
  dropout: 0.5
  subspace_rank: 8
  eps: 1e-8

  lambda_shared_ratio: 0.0
  lambda_residual_ratio: 0.0

training:
  batch: 32
  eval_batch: 256
  epoch: 100
  lr: 0.0005
  weight_decay: 1e-5
  lr_decay: 0.99
  optimizer: Adam

evaluation:
  eval_step: 1
  early_stop_patience: 10




data:
  root: /home/infolab/mnt/mingyu/review_rec/dataset
  cache_dir: /home/infolab/mnt/mingyu/review_rec/review4rec/cached
  word_embedding_file: /home/infolab/mnt/mingyu/review_rec/review4rec/cached/word2vec/GoogleNews-vectors-negative300.bin
  word_embedding_type: "google"
  dataset: Amazon_All_Beauty_18
  word_dim: 300
  review_length: 200
  review_count: 25
  lowest_review_count: 2
  retain_rui: false
  pad_id: 0
  load_review_text: true
  stopword_file: /home/infolab/mnt/mingyu/review_rec/review4rec/cached/word2vec/stopwords.txt
  punctuation_file: /home/infolab/mnt/mingyu/review_rec/review4rec/cached/word2vec/punctuations.txt
  separator: "\t"
  vocab_size : 0

experiment:
  seed: 42
  device: 0
  save_dir: ./outputs
  log_step: 10

stats:
  num_users: 0
  num_items: 0
