# @package _global_

model_name: rmg

model:
  cnn_dim: 100
  id_dim: 100
  kernel_size: 3
  dropout: 0.5
  freeze_word_embedding: false

data:
  dataset: Amazon_Office_Products_14
  type: glove

training:
  lr: 0.001
  batch: 64
  eval_batch: 64
  epoch: 100
  weight_decay: 1e-3
  lr_decay: 0.99
  optimizer: Adam

evaluation:
  eval_step: 1
  early_stop_patience: 10
