# @package _global_

defaults:
  - cfarg
  - _self_

experiment:
  results_dir: ./results/cfarg_fixed
  result_file: ./results/cfarg_fixed/noise_results.csv
noise:
  enabled: true
  type: random_review_replacement
  ratio: 0.1
  side: both
