# @package _global_

defaults:
  - _self_
  - model: base

hydra:
  run:
    dir: .
  output_subdir: null

training:
  batch: 256
  eval_batch: 512
  epoch: 100
  lr: 0.001
  weight_decay: 0.0
  lr_decay: 0.99
  optimizer: Adam

evaluation:
  eval_step: 1
  early_stop_patience: 10
  eval_only: false
  checkpoint_path: null
  sentiment_subset: null

data:
  root: ./dataset
  data_root: ./raw_dataset
  separator: "\t"
  glove_path: ./word2vec/glove.6B.50d.txt
  stopwords_path: ./word2vec/stopwords.txt
  punctuation_path: ./word2vec/punctuations.txt
  dataset: Amazon_All_Beauty_18
  type: None

sentiment:
  model_name: cardiffnlp/twitter-roberta-large-topic-sentiment-latest
  batch_size: 32

experiment:
  seed: 42
  device: 0
  save_dir: ./outputs
  log_step: 10

stats:
  num_users: 0
  num_items: 0
